[[wxWidgets]]
arch = "aarch64"
git-tree-sha1 = "dcc682b62a4d850df9be55d44a4e5c31c808405a"
os = "macos"

    [[wxWidgets.download]]
    sha256 = "8a214d88701cc8cde6626d483507ef09c56c6cd9fb049812b4d341eaa4f4b1f8"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.aarch64-apple-darwin.tar.gz"
[[wxWidgets]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad1e1401b169c757d3630e456e5b39f17d567f79"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "4c9d299329442cb90295a829363d8968ed393704d31487408588699a09737cc8"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[wxWidgets]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ef1e9d03d1d3bb811ebdf11e778cf287c4216df"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "3209105cd6b93779120498fb98da7211aa9b8e3ab0cd49e7312cb098d93ef377"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[wxWidgets]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3247e0d4e58d0acffd73db2e0805d468979e3a4f"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "de5b95859e8261e8f01efdd06768eb6df7b80415ea0f605c5bb157ff888bcf32"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.aarch64-linux-musl-cxx03.tar.gz"
[[wxWidgets]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b26494fc0a50eb7555b0298641ac888eff849722"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "672ec587ac3d2083b57126c96d07b0f8525b8a05eeaacae1c9bd23530e223530"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[wxWidgets]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76795c9eb5cb4d527866a6d6413c86d6db0a4a84"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "7006490d0110bdca4ce657fe1e153bab169a985cb459c4ca8fa09c69d253db64"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[wxWidgets]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6b48cf723d3b929689924d6cc182988720e3e66"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "c4b32e696a21d757b402ce11ab4c0bc38164ebf94595951981fb3629a95b8e4f"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[wxWidgets]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2896b93d363ae5c7a674c5ab598df0ec489b2873"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "bb5d4825be373948afd4b8ddbb27ca09bba7186a16612dc23dbbb36c718f720a"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[wxWidgets]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7eb57e818a05fa9bc5b6443c612301d0896154f"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "eb0853373a6ecf4365b91af8468774347b9d5ae5da39f83cf0f66c115ac5faa2"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[wxWidgets]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2ea934841b15d49a45db058c9b40aa053c2c1d1"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "992fd38e856ee6cff69c1e9e15dfc16d58d8c120a3841a7ac4d75b59eafc4e72"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.i686-linux-gnu-cxx03.tar.gz"
[[wxWidgets]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42e7647ba0283ff66deaeb6d89da8b95a97b1bf3"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "5d530f585c4bf04cfd70d854a7a959e458a27d475729c16e7dccb0cb9658bcb8"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.i686-linux-gnu-cxx11.tar.gz"
[[wxWidgets]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e177c8619a91c64f64bbf233336d5949a8d718a4"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "81c72a866c8370cbd04cb8e7f28d1ac5e936e3519aa831923ce6f7adbce2fda4"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.i686-linux-musl-cxx03.tar.gz"
[[wxWidgets]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ebdcf141eea15696193aa5bf6bd0c1c67ca9bbf"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "1aa8e9f30197ee9f263e97aee914924acea4cba17c7f87c86fcfc90d1e527eb5"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.i686-linux-musl-cxx11.tar.gz"
[[wxWidgets]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6fd4bcce1c128ad24ce0b33e106ffbc91712591"
os = "windows"

    [[wxWidgets.download]]
    sha256 = "538e1b225e00ccd8da933aab0cca3b728b12df5cf91a869745c5d4095db4f243"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[wxWidgets]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89841b0ad076a5a8e0353084d6f1937c49c997cc"
os = "windows"

    [[wxWidgets.download]]
    sha256 = "e36bfa42b2e6b359a1be775113546264b222813f227af40504e534c3b15a3f76"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[wxWidgets]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "798458192a299b1ad24debadf148b9d7ed49743c"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "8d4b2886e42d6d70a6c193fb54350078e24fdc6f646609e50aa7db61c4a33280"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[wxWidgets]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4dbdb3382db604ef85afa8064c4ca44b2fb8f11"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "7ff36e30e0e8b4d6fc424b7b0589774a815172e4f59ae5ab544ecd0e66740483"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[wxWidgets]]
arch = "x86_64"
git-tree-sha1 = "ce8f12d03901f510364def5146cfa1800c504792"
os = "macos"

    [[wxWidgets.download]]
    sha256 = "30b48559a4e7a7241484bc7dec661a764bd553f296bcb3374f770e1faad3fd54"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-apple-darwin.tar.gz"
[[wxWidgets]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bd12c5e9ac62be87980fdcefad61565298e7fca"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "91d9eedc7c40c20c8b7e570989960e8d7b9fb892bdebacf8583462bd93bb6ffe"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[wxWidgets]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a647d0c3ad1338eea4ab2aa4a4cff7df94832dba"
libc = "glibc"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "29ba04ee09c7aa308be6b6839c4baf8e375fe68961108c245ff463e4d884f6d0"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[wxWidgets]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ecc296231827fc07d6714ed0c96313ad8d4b99c6"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "414e5d0c2ca6222c0322c03f3ca13502c9b218fa80d6adb61ed5d7f8ede2115e"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[wxWidgets]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cfe075de6314ffa11a72f0a770e170d02dadd4a"
libc = "musl"
os = "linux"

    [[wxWidgets.download]]
    sha256 = "0fe570e164618ad1dbc5bedb39477f3d80670076e7b19fcb12c7fdbb1b3b4bc2"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[wxWidgets]]
arch = "x86_64"
git-tree-sha1 = "1fc9fb79b3db9407bfa0f41ed240fc8b8d2c0936"
os = "freebsd"

    [[wxWidgets.download]]
    sha256 = "7cd4cffbba7f8401499a1a787c85b15055173eb5443540de9eccb5c864fe3d9e"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-unknown-freebsd.tar.gz"
[[wxWidgets]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a61e57f2240fab6611e1def700c579abad99e5f"
os = "windows"

    [[wxWidgets.download]]
    sha256 = "7ff85422a6173004e134266e4218661c2ea93718085fc4540456774a1b01cfd0"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[wxWidgets]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e005a4bc446164700adbfc258e98bb68a1e7ea7a"
os = "windows"

    [[wxWidgets.download]]
    sha256 = "df42a6d3c21ad40aad19d30c4fbd560e880ddcd54bab6b6ac2efab55a0c3e792"
    url = "https://github.com/JuliaBinaryWrappers/wxWidgets_jll.jl/releases/download/wxWidgets-v3.2.4+0/wxWidgets.v3.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
