# Autogenerated wrapper script for wxWidgets_jll for i686-w64-mingw32-cxx11
export aui, baseu, baseu_net, baseu_xml, core, html, propgrid, qa, ribbon, richtext, stc, wxrc, xrc

using libpng_jll
using JpegTurbo_jll
using Libtiff_jll
using LibCURL_jll
using GTK3_jll
using Zlib_jll
using Expat_jll
JLLWrappers.@generate_wrapper_header("wxWidgets")
JLLWrappers.@declare_library_product(aui, "wxmsw32u_aui_gcc_custom.dll")
JLLWrappers.@declare_library_product(baseu, "wxbase32u_gcc_custom.dll")
JLLWrappers.@declare_library_product(baseu_net, "wxbase32u_net_gcc_custom.dll")
JLLWrappers.@declare_library_product(baseu_xml, "wxbase32u_xml_gcc_custom.dll")
JLLWrappers.@declare_library_product(core, "wxmsw32u_core_gcc_custom.dll")
JLLWrappers.@declare_library_product(html, "wxmsw32u_html_gcc_custom.dll")
JLLWrappers.@declare_library_product(propgrid, "wxmsw32u_propgrid_gcc_custom.dll")
JLLWrappers.@declare_library_product(qa, "wxmsw32u_qa_gcc_custom.dll")
JLLWrappers.@declare_library_product(ribbon, "wxmsw32u_ribbon_gcc_custom.dll")
JLLWrappers.@declare_library_product(richtext, "wxmsw32u_richtext_gcc_custom.dll")
JLLWrappers.@declare_library_product(stc, "wxmsw32u_stc_gcc_custom.dll")
JLLWrappers.@declare_library_product(xrc, "wxmsw32u_xrc_gcc_custom.dll")
JLLWrappers.@declare_executable_product(wxrc)
function __init__()
    JLLWrappers.@generate_init_header(libpng_jll, JpegTurbo_jll, Libtiff_jll, LibCURL_jll, GTK3_jll, Zlib_jll, Expat_jll)
    JLLWrappers.@init_library_product(
        aui,
        "bin\\wxmsw32u_aui_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        baseu,
        "bin\\wxbase32u_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        baseu_net,
        "bin\\wxbase32u_net_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        baseu_xml,
        "bin\\wxbase32u_xml_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        core,
        "bin\\wxmsw32u_core_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        html,
        "bin\\wxmsw32u_html_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        propgrid,
        "bin\\wxmsw32u_propgrid_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        qa,
        "bin\\wxmsw32u_qa_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ribbon,
        "bin\\wxmsw32u_ribbon_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        richtext,
        "bin\\wxmsw32u_richtext_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        stc,
        "bin\\wxmsw32u_stc_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        xrc,
        "bin\\wxmsw32u_xrc_gcc_custom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        wxrc,
        "bin\\wxrc-3.2.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
